import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeftIcon, UserPlusIcon, CalendarIcon, EnvelopeIcon, PhoneIcon, HomeIcon, IdentificationIcon, UserCircleIcon, AcademicCapIcon, BookOpenIcon, ClockIcon, ScaleIcon, TagIcon, CheckCircleIcon, XCircleIcon } from '@heroicons/react/24/outline';
import { supabase } from '../../lib/supabase';
import { useAuth } from '../../contexts/AuthContext';
import { API_URL } from '../../config';

const AddStudent = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [studentId, setStudentId] = useState(null);
  const [studentData, setStudentData] = useState({
    auth_user_id: null
  });
  const [credentials, setCredentials] = useState({
    username: '',
    password: '',
    show: false,
    showPassword: false
  });
  const [loadingInitialData, setLoadingInitialData] = useState(true);
  const [departments, setDepartments] = useState([]);
  const [courses, setCourses] = useState([]);
  
  const [formData, setFormData] = useState({
    // Personal Information
    full_name: '',
    name: '',
    email: '',
    phone: '',
    gender: 'male',
    date_of_birth: '',
    blood_group: 'O+',
    address: '',
    
    // Academic Information
    register_number: '',
    roll_no: '',
    department_id: '',
    course_id: '',
    year: 1,
    current_semester: 1,
    section: 'A',
    admission_year: new Date().getFullYear(),
    admission_date: new Date().toISOString().split('T')[0],
    
    // Family Information
    father_name: '',
    mother_name: '',
    guardian_name: '',
    guardian_phone: '',
    annual_income: '',
    
    // Additional Information
    status: 'active',
    type: 'day_scholar',
    quota: 'GENERAL',
    category: 'GENERAL',
    quota_type: 'GENERAL',
    hostel_required: false,
    transport_required: false,
    first_graduate: false,

    // System Fields (id will be auto-generated by Supabase)
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  });

  // Use Vite env var if provided, otherwise fall back to shared config
  const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || API_URL; // API_URL includes /api by default
  const { user } = useAuth();

  // Blood groups and other constants
  const bloodGroups = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'];
  const genders = ['male', 'female', 'other'];
  const years = [1, 2, 3, 4, 5];
  const semesters = [1, 2, 3, 4, 5, 6, 7, 8];
  const sections = ['A', 'B', 'C', 'D'];
  const statuses = ['active', 'inactive', 'suspended', 'graduated'];
  const studentTypes = ['day_scholar', 'hosteller'];
  const quotaTypes = ['GENERAL', 'SC', 'ST', 'OBC', 'EWS', 'OTHER'];
  const categories = ['GENERAL', 'SPORTS', 'NCC', 'NSS', 'PHYSICALLY_CHALLENGED'];
  
  // Load initial data
  useEffect(() => {
    const loadData = async () => {
      try {
        setLoadingInitialData(true);
        
        // Fetch departments and courses in parallel
        // Fetch departments and courses with all required fields
        const [
          { data: deptData, error: deptError },
          { data: coursesData, error: coursesError }
        ] = await Promise.all([
          supabase.from('departments').select('*').order('name'),
          supabase.from('courses').select('*, department_id').order('name')
        ]);
        
        if (deptError) throw deptError;
        if (coursesError) throw coursesError;
        
        console.log('Departments:', deptData);
        console.log('Courses:', coursesData);
        
        setDepartments(deptData || []);
        setCourses(coursesData || []);
        
        // Log the first course to check its structure
        if (coursesData && coursesData.length > 0) {
          console.log('First course structure:', coursesData[0]);
        }
        
        // Generate a default register number based on current year and random number
        const currentYear = new Date().getFullYear().toString().slice(-2);
        const randomNum = Math.floor(1000 + Math.random() * 9000);
        const defaultRegisterNumber = `REG${currentYear}${randomNum}`;
        
        // Set default values
        setFormData(prev => ({
          ...prev,
          register_number: defaultRegisterNumber,
          admission_year: new Date().getFullYear(),
          admission_date: new Date().toISOString().split('T')[0],
          course_id: ''
        }));
        
      } catch (err) {
        console.error('Error loading initial data:', err);
        setError('Failed to load required data. Please refresh the page.');
      } finally {
        setLoadingInitialData(false);
      }
    };
    
    loadData();
  }, []);

  // Handle form input changes
  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;
    
    if (name === 'department_id') {
      // When department changes, reset the course selection
      setFormData(prev => {
        // Find the selected department
        const selectedDept = departments.find(dept => dept.id === Number(value));
        
        // Get the first course in the selected department (if any)
        const firstCourseInDept = courses.find(course => 
          course.department_id === Number(value)
        );
        
        return {
          ...prev,
          [name]: value,
          course_id: firstCourseInDept ? firstCourseInDept.id : '',
          // Also update the department name for display
          department_name: selectedDept ? selectedDept.name : ''
        };
      });
      return;
    }
    
    // Handle course selection
    if (name === 'course_id') {
      setFormData(prev => {
        // Find the selected course
        const selectedCourse = courses.find(course => course.id === value);
        return {
          ...prev,
          [name]: value,
          // Update the course name for display
          course_name: selectedCourse ? selectedCourse.name : ''
        };
      });
      return;
    }
    
    // For all other fields
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }));
  };

  const checkEmailExists = async (email) => {
    const { data, error } = await supabase
      .from('students')
      .select('email')
      .eq('email', email)
      .limit(1);
    
    return { exists: Array.isArray(data) && data.length > 0, error };
  };

  const generateTemporaryPassword = () => {
    // Generate a random password with 12 characters
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()';
    return Array(12).fill('').map(() => chars[Math.floor(Math.random() * chars.length)]).join('');
  };

  // Handle form submission
  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError('');
    setSuccess('');

    try {
      // Basic validation
      if (!formData.email || !formData.full_name) {
        throw new Error('Email and full name are required');
      }

      // Check if email exists in students table
      const { exists: emailExists, error: emailCheckError } = await checkEmailExists(formData.email);
      
      if (emailExists) {
        throw new Error('A student with this email already exists');
      }
      
      if (emailCheckError) {
        console.warn('Warning: Could not verify email uniqueness:', emailCheckError.message);
        // Continue anyway, as this is just a pre-check
      }
      // Form validation
      const requiredFields = [
        'full_name', 'email', 'phone', 'course_id', 
        'current_semester', 'admission_year', 'department_id'
      ];
      
      const missingFields = requiredFields.filter(field => !formData[field]);
      
      if (missingFields.length > 0) {
        throw new Error(`Missing required fields: ${missingFields.join(', ')}`);
      }

      console.log('Form data being submitted:', JSON.stringify(formData, null, 2));
      
      // Create student data for backend API
      const studentData = {
        full_name: formData.full_name.trim(),
        name: (formData.name || formData.full_name).trim(),
        email: formData.email.trim().toLowerCase(),
        phone: formData.phone.trim(),
        gender: formData.gender || 'male',
        date_of_birth: formData.date_of_birth || null,
        blood_group: formData.blood_group || 'O+',
        address: formData.address?.trim() || '',
        course_id: formData.course_id,
        department_id: formData.department_id,
        year: parseInt(formData.year, 10) || 1,
        current_semester: parseInt(formData.current_semester, 10) || 1,
        section: formData.section || 'A',
        admission_year: parseInt(formData.admission_year, 10) || new Date().getFullYear(),
        admission_date: formData.admission_date || new Date().toISOString().split('T')[0],
        father_name: formData.father_name?.trim() || '',
        mother_name: formData.mother_name?.trim() || '',
        guardian_name: formData.guardian_name?.trim() || '',
        guardian_phone: formData.guardian_phone?.trim() || '',
        annual_income: formData.annual_income || null,
        status: formData.status || 'active',
        type: formData.type || 'day_scholar',
        quota: formData.quota || 'GENERAL',
        category: formData.category || 'GENERAL',
        quota_type: formData.quota_type || 'GENERAL',
        hostel_required: Boolean(formData.hostel_required),
        transport_required: Boolean(formData.transport_required),
        first_graduate: Boolean(formData.first_graduate)
      };

      console.log('Student data to be sent to API:', JSON.stringify(studentData, null, 2));
      
      // Get the current session
      const { data: { session } } = await supabase.auth.getSession();
      
      if (!session) {
        throw new Error('No active session. Please log in again.');
      }

      // Generate a temporary password
      const temporaryPassword = generateTemporaryPassword();
      
      // Include the temporary password in the student data
      const studentDataWithPassword = {
        ...studentData,
        password: temporaryPassword
      };
      
      console.log('Sending student data with temporary password');
      
      // Call the backend API to create the student
      const response = await fetch(`${API_BASE_URL}/students`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${session.access_token}`
        },
        body: JSON.stringify(studentDataWithPassword)
      });

      const result = await response.json();
      
      if (!response.ok) {
        console.error('Backend error response:', result);
        
        // Handle specific error cases
        if (response.status === 400) {
          throw new Error(result.error || 'Invalid data provided. Please check all fields.');
        } else if (response.status === 401) {
          throw new Error('Session expired. Please log in again.');
        } else if (response.status === 409) {
          throw new Error('A student with this email or register number already exists.');
        } else if (response.status === 500) {
          throw new Error('Server error. Please try again later or contact support.');
        } else {
          throw new Error(result.error || result.details || 'Failed to create student');
        }
      }
      
      // The backend handles auth user and student creation
      const student = result.data;
      const studentEmail = result.email || studentData.email;
      
      if (!temporaryPassword) {
        throw new Error('Failed to generate temporary password. Please try again.');
      }
      
      // Store the student ID from the response
      if (student && student.id) {
        setStudentId(student.id);
        setStudentData(prev => ({
          ...prev,
          id: student.id,
          auth_user_id: student.auth_user_id
        }));
      } else {
        console.error('Student ID not found in response:', result);
        throw new Error('Failed to retrieve student ID from the server');
      }
      
      // Reset form before showing success message
      resetForm();
      
      // Store credentials in state to show in a modal
      setCredentials({
        username: studentEmail,
        password: temporaryPassword,
        fullName: studentData.full_name,
        registerNumber: result.register_number || student.register_number || '',
        show: true
      });
      
      // Set success message
      setSuccess('Student added successfully! The login credentials are displayed below.');
    } catch (err) {
      console.error('Error adding student:', err);
      setError(err.message || 'Failed to add student. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const resetForm = () => {
    setFormData({
      full_name: '',
      name: '',
      email: '',
      phone: '',
      gender: 'male',
      date_of_birth: '',
      blood_group: 'O+',
      address: '',
      register_number: `REG${new Date().getFullYear().toString().slice(-2)}${Math.floor(1000 + Math.random() * 9000)}`,
      roll_no: '',
      department_id: '',
      course_id: '',
      year: 1,
      current_semester: 1,
      section: 'A',
      admission_year: new Date().getFullYear(),
      admission_date: new Date().toISOString().split('T')[0],
      father_name: '',
      mother_name: '',
      guardian_name: '',
      guardian_phone: '',
      annual_income: '',
      status: 'active',
      type: 'day_scholar',
      quota: 'GENERAL',
      category: 'GENERAL',
      quota_type: 'GENERAL',
      hostel_required: false,
      transport_required: false,
      first_graduate: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString()
    });
    setError('');
  };

  if (loading || loadingInitialData) {
    return (
      <div className="min-h-screen bg-gray-50 py-8 px-4 sm:px-6 lg:px-8 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-indigo-600 mx-auto"></div>
          <p className="mt-4 text-gray-600">Loading student form...</p>
        </div>
      </div>
    );
  }

  const activateStudentLogin = async () => {
    try {
      setLoading(true);
      
      // Call the backend to activate the student login
      const response = await fetch(`${API_BASE_URL}/students/${studentId}/activate-login`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${user.token}`
        }
      });

      const result = await response.json();

      if (!response.ok) {
        throw new Error(result.error || 'Failed to activate student login');
      }

      // Show success message with the temporary password if available
      if (result.temporary_password) {
        setCredentials(prev => ({
          ...prev,
          password: result.temporary_password,
          showPassword: true
        }));
        
        // Show success message
        setSuccess('Student login activated successfully!');
        
        // Update the student data with the new auth_user_id
        if (result.auth_user_id) {
          setStudentData(prev => ({
            ...prev,
            auth_user_id: result.auth_user_id
          }));
        }
      }
    } catch (error) {
      console.error('Error activating student login:', error);
      setError(error.message || 'Failed to activate student login');
    } finally {
      setLoading(false);
    }
  };

  const CredentialsModal = () => (
    <div className="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full flex items-center justify-center">
      <div className="bg-white p-6 rounded-lg shadow-xl max-w-md w-full">
        <h3 className="text-lg font-bold mb-4">Student Account Created</h3>
        <div className="space-y-4">
          <p>The following credentials have been created for the student:</p>
          <div className="bg-gray-50 p-4 rounded space-y-2">
            <div className="flex justify-between items-center">
              <p><span className="font-semibold">Username:</span> {credentials.username}</p>
            </div>
            <div className="flex justify-between items-center">
              <p><span className="font-semibold">Password:</span> 
                {credentials.showPassword ? credentials.password : '••••••••'}
              </p>
              <button
                type="button"
                onClick={() => setCredentials(prev => ({
                  ...prev,
                  showPassword: !prev.showPassword
                }))}
                className="text-sm text-indigo-600 hover:text-indigo-800"
              >
                {credentials.showPassword ? 'Hide' : 'Show'}
              </button>
            </div>
            {credentials.showPassword && (
              <p className="text-xs text-gray-500 mt-1">
                Please save this password securely. It won't be shown again.
              </p>
            )}
          </div>
          <p className="text-sm text-gray-600">
            Please provide these credentials to the student. They should change their password after first login.
          </p>
          <div className="flex flex-col space-y-3">
            <button
              type="button"
              onClick={activateStudentLogin}
              disabled={loading || studentData.auth_user_id}
              className={`w-full px-4 py-2 text-white rounded transition-colors ${
                studentData.auth_user_id 
                  ? 'bg-green-700 cursor-not-allowed' 
                  : loading 
                    ? 'bg-green-400' 
                    : 'bg-green-600 hover:bg-green-700'
              }`}
            >
              {loading ? 'Activating...' : 
               studentData.auth_user_id ? 'Login Activated' : 
               'Activate Login'}
            </button>
            <div className="flex justify-between space-x-3">
              <button
                type="button"
                onClick={() => {
                  navigator.clipboard.writeText(`Username: ${credentials.username}\nPassword: ${credentials.password}`);
                  alert('Credentials copied to clipboard!');
                }}
                className="flex-1 px-4 py-2 bg-gray-200 text-gray-800 rounded hover:bg-gray-300 transition-colors"
              >
                Copy to Clipboard
              </button>
              <button
                type="button"
                onClick={() => setCredentials({...credentials, show: false})}
                className="flex-1 px-4 py-2 bg-indigo-600 text-white rounded hover:bg-indigo-700 transition-colors"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );

  return (
    <div className="min-h-screen bg-gray-50 py-8 px-4 sm:px-6 lg:px-8">
      <div className="max-w-7xl mx-auto">
        <div className="md:flex md:items-center md:justify-between mb-8">
          <div className="flex-1 min-w-0">
            <h2 className="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:truncate">
              Add New Student
            </h2>
          </div>
          <div className="mt-4 flex md:mt-0 md:ml-4">
            <button
              type="button"
              onClick={() => navigate(-1)}
              className="inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
            >
              <ArrowLeftIcon className="-ml-1 mr-2 h-5 w-5 text-gray-500" />
              Back
            </button>
          </div>
        </div>

        {error && (
          <div className="mb-4 bg-red-50 border-l-4 border-red-400 p-4">
            <div className="flex">
              <div className="flex-shrink-0">
                <XCircleIcon className="h-5 w-5 text-red-400" />
              </div>
              <div className="ml-3">
                <p className="text-sm text-red-700">{error}</p>
              </div>
            </div>
          </div>
        )}

        {credentials.show && <CredentialsModal />}

        <form onSubmit={handleSubmit} className="space-y-6">
          {/* Personal Information Section */}
          <div className="bg-white shadow px-4 py-5 sm:rounded-lg sm:p-6">
            <div className="md:grid md:grid-cols-3 md:gap-6">
              <div className="md:col-span-1">
                <h3 className="text-lg font-medium leading-6 text-gray-900">Personal Information</h3>
                <p className="mt-1 text-sm text-gray-500">Enter the student's personal details.</p>
              </div>
              <div className="mt-5 md:mt-0 md:col-span-2">
                <div className="grid grid-cols-6 gap-6">
                  <div className="col-span-6 sm:col-span-3">
                    <label htmlFor="full_name" className="block text-sm font-medium text-gray-700">
                      Full Name *
                    </label>
                    <div className="mt-1 relative rounded-md shadow-sm">
                      <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                        <UserCircleIcon className="h-5 w-5 text-gray-400" />
                      </div>
                      <input
                        type="text"
                        name="full_name"
                        id="full_name"
                        value={formData.full_name}
                        onChange={handleChange}
                        className="focus:ring-indigo-500 focus:border-indigo-500 block w-full pl-10 sm:text-sm border-gray-300 rounded-md"
                        placeholder="John Doe"
                        required
                      />
                    </div>
                  </div>

                  <div className="col-span-6 sm:col-span-3">
                    <label htmlFor="email" className="block text-sm font-medium text-gray-700">
                      Email Address
                    </label>
                    <div className="mt-1 relative rounded-md shadow-sm">
                      <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                        <EnvelopeIcon className="h-5 w-5 text-gray-400" />
                      </div>
                      <input
                        type="email"
                        name="email"
                        id="email"
                        value={formData.email}
                        onChange={handleChange}
                        className="focus:ring-indigo-500 focus:border-indigo-500 block w-full pl-10 sm:text-sm border-gray-300 rounded-md"
                        placeholder="john@example.com"
                      />
                    </div>
                  </div>

                  <div className="col-span-6 sm:col-span-3">
                    <label htmlFor="phone" className="block text-sm font-medium text-gray-700">
                      Phone Number
                    </label>
                    <div className="mt-1 relative rounded-md shadow-sm">
                      <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                        <PhoneIcon className="h-5 w-5 text-gray-400" />
                      </div>
                      <input
                        type="tel"
                        name="phone"
                        id="phone"
                        value={formData.phone}
                        onChange={handleChange}
                        className="focus:ring-indigo-500 focus:border-indigo-500 block w-full pl-10 sm:text-sm border-gray-300 rounded-md"
                        placeholder="+91 9876543210"
                      />
                    </div>
                  </div>

                  <div className="col-span-6 sm:col-span-3">
                    <label htmlFor="gender" className="block text-sm font-medium text-gray-700">
                      Gender
                    </label>
                    <select
                      id="gender"
                      name="gender"
                      value={formData.gender}
                      onChange={handleChange}
                      className="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                    >
                      {genders.map((gender) => (
                        <option key={gender} value={gender}>
                          {gender.charAt(0).toUpperCase() + gender.slice(1)}
                        </option>
                      ))}
                    </select>
                  </div>

                  <div className="col-span-6 sm:col-span-3">
                    <label htmlFor="date_of_birth" className="block text-sm font-medium text-gray-700">
                      Date of Birth
                    </label>
                    <div className="mt-1 relative rounded-md shadow-sm">
                      <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                        <CalendarIcon className="h-5 w-5 text-gray-400" />
                      </div>
                      <input
                        type="date"
                        name="date_of_birth"
                        id="date_of_birth"
                        value={formData.date_of_birth}
                        onChange={handleChange}
                        className="focus:ring-indigo-500 focus:border-indigo-500 block w-full pl-10 sm:text-sm border-gray-300 rounded-md"
                      />
                    </div>
                  </div>

                  <div className="col-span-6 sm:col-span-3">
                    <label htmlFor="blood_group" className="block text-sm font-medium text-gray-700">
                      Blood Group
                    </label>
                    <select
                      id="blood_group"
                      name="blood_group"
                      value={formData.blood_group}
                      onChange={handleChange}
                      className="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                    >
                      {bloodGroups.map((group) => (
                        <option key={group} value={group}>
                          {group}
                        </option>
                      ))}
                    </select>
                  </div>

                  <div className="col-span-6">
                    <label htmlFor="address" className="block text-sm font-medium text-gray-700">
                      Address
                    </label>
                    <div className="mt-1">
                      <textarea
                        id="address"
                        name="address"
                        rows={3}
                        value={formData.address}
                        onChange={handleChange}
                        className="shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border border-gray-300 rounded-md"
                        placeholder="123 Main St, City, State, PIN"
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Academic Information Section */}
          <div className="bg-white shadow px-4 py-5 sm:rounded-lg sm:p-6">
            <div className="md:grid md:grid-cols-3 md:gap-6">
              <div className="md:col-span-1">
                <h3 className="text-lg font-medium leading-6 text-gray-900">Academic Information</h3>
                <p className="mt-1 text-sm text-gray-500">Student's academic details and enrollment information.</p>
              </div>
              <div className="mt-5 md:mt-0 md:col-span-2">
                <div className="grid grid-cols-6 gap-6">
                  <div className="col-span-6 sm:col-span-3">
                    <label htmlFor="register_number" className="block text-sm font-medium text-gray-700">
                      Register Number *
                    </label>
                    <div className="mt-1 relative rounded-md shadow-sm">
                      <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                        <IdentificationIcon className="h-5 w-5 text-gray-400" />
                      </div>
                      <input
                        type="text"
                        name="register_number"
                        id="register_number"
                        value={formData.register_number}
                        onChange={handleChange}
                        className="focus:ring-indigo-500 focus:border-indigo-500 block w-full pl-10 sm:text-sm border-gray-300 rounded-md"
                        required
                      />
                    </div>
                  </div>

                  <div className="col-span-6 sm:col-span-3">
                    <label htmlFor="roll_no" className="block text-sm font-medium text-gray-700">
                      Roll Number
                    </label>
                    <input
                      type="text"
                      name="roll_no"
                      id="roll_no"
                      value={formData.roll_no}
                      onChange={handleChange}
                      className="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"
                    />
                  </div>

                  <div className="col-span-6 sm:col-span-3">
                    <label htmlFor="department_id" className="block text-sm font-medium text-gray-700">
                      Department *
                    </label>
                    <select
                      id="department_id"
                      name="department_id"
                      value={formData.department_id}
                      onChange={handleChange}
                      className="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                      required
                    >
                      <option value="">Select Department</option>
                      {departments.map((dept) => (
                        <option key={dept.id} value={Number(dept.id)}>
                          {dept.name}
                        </option>
                      ))}
                    </select>
                  </div>

                  <div className="col-span-6 sm:col-span-3">
                    <label htmlFor="course_id" className="block text-sm font-medium text-gray-700">
                      Course *
                    </label>
                    <select
                      id="course_id"
                      name="course_id"
                      value={formData.course_id}
                      onChange={handleChange}
                      className="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                      required
                      disabled={!formData.department_id}
                    >
                      <option value="">
                        {formData.department_id ? 'Select a course' : 'Please select a department first'}
                      </option>
                      {courses && courses
                        .filter(course => {
                          // If no department is selected, don't show any courses
                          if (!formData.department_id) return false;
                          
                          // Convert both IDs to numbers for comparison
                          const courseDeptId = Number(course.department_id);
                          const selectedDeptId = Number(formData.department_id);
                          
                          // Log for debugging
                          console.log('Course department ID:', courseDeptId, 
                                     'Selected department ID:', selectedDeptId, 
                                     'Match:', courseDeptId === selectedDeptId);
                          
                          return courseDeptId === selectedDeptId;
                        })
                        .map((course) => (
                          <option key={course.id} value={course.id}>
                            {course.name}
                          </option>
                        ))}
                    </select>
                  </div>

                  <div className="col-span-6 sm:col-span-2">
                    <label htmlFor="year" className="block text-sm font-medium text-gray-700">
                      Academic Year
                    </label>
                    <select
                      id="year"
                      name="year"
                      value={formData.year}
                      onChange={handleChange}
                      className="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                    >
                      {years.map((year) => (
                        <option key={year} value={year}>
                          Year {year}
                        </option>
                      ))}
                    </select>
                  </div>

                  <div className="col-span-6 sm:col-span-2">
                    <label htmlFor="current_semester" className="block text-sm font-medium text-gray-700">
                      Current Semester
                    </label>
                    <select
                      id="current_semester"
                      name="current_semester"
                      value={formData.current_semester}
                      onChange={handleChange}
                      className="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                    >
                      {semesters.map((sem) => (
                        <option key={sem} value={sem}>
                          Semester {sem}
                        </option>
                      ))}
                    </select>
                  </div>

                  <div className="col-span-6 sm:col-span-2">
                    <label htmlFor="section" className="block text-sm font-medium text-gray-700">
                      Section
                    </label>
                    <select
                      id="section"
                      name="section"
                      value={formData.section}
                      onChange={handleChange}
                      className="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                    >
                      {sections.map((sec) => (
                        <option key={sec} value={sec}>
                          Section {sec}
                        </option>
                      ))}
                    </select>
                  </div>

                  <div className="col-span-6 sm:col-span-3">
                    <label htmlFor="admission_year" className="block text-sm font-medium text-gray-700">
                      Admission Year
                    </label>
                    <div className="mt-1 relative rounded-md shadow-sm">
                      <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                        <CalendarIcon className="h-5 w-5 text-gray-400" />
                      </div>
                      <input
                        type="number"
                        name="admission_year"
                        id="admission_year"
                        min="2000"
                        max="2099"
                        step="1"
                        value={formData.admission_year}
                        onChange={handleChange}
                        className="focus:ring-indigo-500 focus:border-indigo-500 block w-full pl-10 sm:text-sm border-gray-300 rounded-md"
                      />
                    </div>
                  </div>

                  <div className="col-span-6 sm:col-span-3">
                    <label htmlFor="admission_date" className="block text-sm font-medium text-gray-700">
                      Admission Date
                    </label>
                    <div className="mt-1 relative rounded-md shadow-sm">
                      <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                        <CalendarIcon className="h-5 w-5 text-gray-400" />
                      </div>
                      <input
                        type="date"
                        name="admission_date"
                        id="admission_date"
                        value={formData.admission_date}
                        onChange={handleChange}
                        className="focus:ring-indigo-500 focus:border-indigo-500 block w-full pl-10 sm:text-sm border-gray-300 rounded-md"
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Family Information Section */}
          <div className="bg-white shadow px-4 py-5 sm:rounded-lg sm:p-6">
            <div className="md:grid md:grid-cols-3 md:gap-6">
              <div className="md:col-span-1">
                <h3 className="text-lg font-medium leading-6 text-gray-900">Family Information</h3>
                <p className="mt-1 text-sm text-gray-500">Student's family and guardian details.</p>
              </div>
              <div className="mt-5 md:mt-0 md:col-span-2">
                <div className="grid grid-cols-6 gap-6">
                  <div className="col-span-6 sm:col-span-3">
                    <label htmlFor="father_name" className="block text-sm font-medium text-gray-700">
                      Father's Name
                    </label>
                    <input
                      type="text"
                      name="father_name"
                      id="father_name"
                      value={formData.father_name}
                      onChange={handleChange}
                      className="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"
                      placeholder="Father's full name"
                    />
                  </div>

                  <div className="col-span-6 sm:col-span-3">
                    <label htmlFor="mother_name" className="block text-sm font-medium text-gray-700">
                      Mother's Name
                    </label>
                    <input
                      type="text"
                      name="mother_name"
                      id="mother_name"
                      value={formData.mother_name}
                      onChange={handleChange}
                      className="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"
                      placeholder="Mother's full name"
                    />
                  </div>

                  <div className="col-span-6 sm:col-span-3">
                    <label htmlFor="guardian_name" className="block text-sm font-medium text-gray-700">
                      Guardian Name
                    </label>
                    <input
                      type="text"
                      name="guardian_name"
                      id="guardian_name"
                      value={formData.guardian_name}
                      onChange={handleChange}
                      className="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md"
                      placeholder="If different from parents"
                    />
                  </div>

                  <div className="col-span-6 sm:col-span-3">
                    <label htmlFor="guardian_phone" className="block text-sm font-medium text-gray-700">
                      Guardian Phone
                    </label>
                    <div className="mt-1 relative rounded-md shadow-sm">
                      <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                        <PhoneIcon className="h-5 w-5 text-gray-400" />
                      </div>
                      <input
                        type="tel"
                        name="guardian_phone"
                        id="guardian_phone"
                        value={formData.guardian_phone}
                        onChange={handleChange}
                        className="focus:ring-indigo-500 focus:border-indigo-500 block w-full pl-10 sm:text-sm border-gray-300 rounded-md"
                        placeholder="+91 9876543210"
                      />
                    </div>
                  </div>

                  <div className="col-span-6 sm:col-span-3">
                    <label htmlFor="annual_income" className="block text-sm font-medium text-gray-700">
                      Annual Income (INR)
                    </label>
                    <div className="mt-1 relative rounded-md shadow-sm">
                      <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                        <span className="text-gray-500 sm:text-sm">₹</span>
                      </div>
                      <input
                        type="number"
                        name="annual_income"
                        id="annual_income"
                        value={formData.annual_income}
                        onChange={handleChange}
                        className="focus:ring-indigo-500 focus:border-indigo-500 block w-full pl-7 pr-12 sm:text-sm border-gray-300 rounded-md"
                        placeholder="0.00"
                        min="0"
                        step="1000"
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Additional Information Section */}
          <div className="bg-white shadow px-4 py-5 sm:rounded-lg sm:p-6">
            <div className="md:grid md:grid-cols-3 md:gap-6">
              <div className="md:col-span-1">
                <h3 className="text-lg font-medium leading-6 text-gray-900">Additional Information</h3>
                <p className="mt-1 text-sm text-gray-500">Other relevant student information.</p>
              </div>
              <div className="mt-5 md:mt-0 md:col-span-2">
                <div className="grid grid-cols-6 gap-6">
                  <div className="col-span-6 sm:col-span-3">
                    <label htmlFor="status" className="block text-sm font-medium text-gray-700">
                      Status
                    </label>
                    <select
                      id="status"
                      name="status"
                      value={formData.status}
                      onChange={handleChange}
                      className="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                    >
                      {statuses.map((status) => (
                        <option key={status} value={status}>
                          {status.charAt(0).toUpperCase() + status.slice(1)}
                        </option>
                      ))}
                    </select>
                  </div>

                  <div className="col-span-6 sm:col-span-3">
                    <label htmlFor="type" className="block text-sm font-medium text-gray-700">
                      Student Type
                    </label>
                    <select
                      id="type"
                      name="type"
                      value={formData.type}
                      onChange={handleChange}
                      className="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                    >
                      {studentTypes.map((type) => (
                        <option key={type} value={type}>
                          {type.split('_').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ')}
                        </option>
                      ))}
                    </select>
                  </div>

                  <div className="col-span-6 sm:col-span-2">
                    <label htmlFor="quota" className="block text-sm font-medium text-gray-700">
                      Quota
                    </label>
                    <select
                      id="quota"
                      name="quota"
                      value={formData.quota}
                      onChange={handleChange}
                      className="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                    >
                      {quotaTypes.map((quota) => (
                        <option key={quota} value={quota}>
                          {quota}
                        </option>
                      ))}
                    </select>
                  </div>

                  <div className="col-span-6 sm:col-span-2">
                    <label htmlFor="category" className="block text-sm font-medium text-gray-700">
                      Category
                    </label>
                    <select
                      id="category"
                      name="category"
                      value={formData.category}
                      onChange={handleChange}
                      className="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                    >
                      {categories.map((category) => (
                        <option key={category} value={category}>
                          {category.split('_').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ')}
                        </option>
                      ))}
                    </select>
                  </div>

                  <div className="col-span-6 sm:col-span-2">
                    <label htmlFor="quota_type" className="block text-sm font-medium text-gray-700">
                      Quota Type
                    </label>
                    <select
                      id="quota_type"
                      name="quota_type"
                      value={formData.quota_type}
                      onChange={handleChange}
                      className="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                    >
                      {quotaTypes.map((type) => (
                        <option key={type} value={type}>
                          {type}
                        </option>
                      ))}
                    </select>
                  </div>

                  <div className="col-span-6">
                    <div className="flex items-start">
                      <div className="flex items-center h-5">
                        <input
                          id="hostel_required"
                          name="hostel_required"
                          type="checkbox"
                          checked={formData.hostel_required}
                          onChange={handleChange}
                          className="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300 rounded"
                        />
                      </div>
                      <div className="ml-3 text-sm">
                        <label htmlFor="hostel_required" className="font-medium text-gray-700">
                          Hostel Accommodation Required
                        </label>
                        <p className="text-gray-500">Check if the student requires hostel accommodation.</p>
                      </div>
                    </div>
                  </div>

                  <div className="col-span-6">
                    <div className="flex items-start">
                      <div className="flex items-center h-5">
                        <input
                          id="transport_required"
                          name="transport_required"
                          type="checkbox"
                          checked={formData.transport_required}
                          onChange={handleChange}
                          className="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300 rounded"
                        />
                      </div>
                      <div className="ml-3 text-sm">
                        <label htmlFor="transport_required" className="font-medium text-gray-700">
                          Transport Facility Required
                        </label>
                        <p className="text-gray-500">Check if the student requires transportation facility.</p>
                      </div>
                    </div>
                  </div>

                  <div className="col-span-6">
                    <div className="flex items-start">
                      <div className="flex items-center h-5">
                        <input
                          id="first_graduate"
                          name="first_graduate"
                          type="checkbox"
                          checked={formData.first_graduate}
                          onChange={handleChange}
                          className="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300 rounded"
                        />
                      </div>
                      <div className="ml-3 text-sm">
                        <label htmlFor="first_graduate" className="font-medium text-gray-700">
                          First Graduate in Family
                        </label>
                        <p className="text-gray-500">Check if the student is the first graduate in their family.</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Form Actions */}
          <div className="flex justify-end space-x-3">
            <button
              type="button"
              onClick={() => navigate(-1)}
              className="bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
            >
              Cancel
            </button>
            <button
              type="button"
              onClick={() => {
                // Reset form
                setFormData({
                  full_name: '',
                  name: '',
                  email: '',
                  phone: '',
                  gender: 'male',
                  date_of_birth: '',
                  blood_group: 'O+',
                  address: '',
                  register_number: `REG${new Date().getFullYear().toString().slice(-2)}${Math.floor(1000 + Math.random() * 9000)}`,
                  roll_no: '',
                  department_id: '',
                  course_id: courses[0]?.id || '',
                  year: 1,
                  current_semester: 1,
                  section: 'A',
                  admission_year: new Date().getFullYear(),
                  admission_date: new Date().toISOString().split('T')[0],
                  father_name: '',
                  mother_name: '',
                  guardian_name: '',
                  guardian_phone: '',
                  annual_income: '',
                  status: 'active',
                  type: 'day_scholar',
                  quota: 'GENERAL',
                  category: 'GENERAL',
                  quota_type: 'GENERAL',
                  hostel_required: false,
                  transport_required: false,
                  first_graduate: false,
                  created_at: new Date().toISOString(),
                  updated_at: new Date().toISOString()
                });
                setError('');
              }}
              className="bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
            >
              Reset Form
            </button>
            <button
              type="submit"
              disabled={loading}
              className="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {loading ? (
                <>
                  <svg className="animate-spin -ml-1 mr-2 h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                  </svg>
                  Saving...
                </>
              ) : (
                <>
                  <UserPlusIcon className="-ml-1 mr-2 h-5 w-5" />
                  Save Student

                </>
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default AddStudent;
